- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup

- name: python
  include_role:
    name: common
    tasks_from: python.yaml

- name: systemd
  include_role:
    name: common
    tasks_from: systemd.yaml